// Generated by uniffi-bindgen-react-native
#import "WhipSsh.h"

extern "C" void whip_set_reverse_control_recovery_directory(const char *path);

static void configureRecoveryDirectory() {
    NSURL *support = [[NSFileManager defaultManager] URLsForDirectory:NSApplicationSupportDirectory
                                                          inDomains:NSUserDomainMask].firstObject;
    NSURL *directory = [support URLByAppendingPathComponent:@"WhipReverseControl" isDirectory:YES];
    if ([[NSFileManager defaultManager] createDirectoryAtURL:directory
                                withIntermediateDirectories:YES attributes:nil error:nil]) {
        [directory setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:nil];
        whip_set_reverse_control_recovery_directory(directory.path.UTF8String);
    }
}

namespace uniffi_generated {
    using namespace facebook::react;
    /**
    * ObjC++ class for module 'NativeWhipSsh'
    */
    class JSI_EXPORT NativeWhipSshSpecJSI : public ObjCTurboModule {
    public:
        NativeWhipSshSpecJSI(const ObjCTurboModule::InitParams &params);
        std::shared_ptr<CallInvoker> callInvoker;
    };

    static facebook::jsi::Value __hostFunction_WhipSsh_installRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        auto& tm = static_cast<NativeWhipSshSpecJSI&>(turboModule);
        auto jsInvoker = tm.callInvoker;
        configureRecoveryDirectory();
        uint8_t result = whipssh::installRustCrate(rt, jsInvoker);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_WhipSsh_cleanupRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        uint8_t result = whipssh::cleanupRustCrate(rt);
        return facebook::jsi::Value(rt, result);
    }

    NativeWhipSshSpecJSI::NativeWhipSshSpecJSI(const ObjCTurboModule::InitParams &params)
        : ObjCTurboModule(params), callInvoker(params.jsInvoker) {
            this->methodMap_["installRustCrate"] = MethodMetadata {1, __hostFunction_WhipSsh_installRustCrate};
            this->methodMap_["cleanupRustCrate"] = MethodMetadata {1, __hostFunction_WhipSsh_cleanupRustCrate};
    }
} // namespace uniffi_generated

@implementation WhipSsh
RCT_EXPORT_MODULE()

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED

// Automated testing checks whipssh
// by comparing the whole line here.
/*
- (NSNumber *)multiply:(double)a b:(double)b {
    NSNumber *result = @(whipssh::multiply(a, b));
}
*/

- (NSNumber *)installRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (NSNumber *)cleanupRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<uniffi_generated::NativeWhipSshSpecJSI>(params);
}
#endif

@end
