// Generated by uniffi-bindgen-react-native
package com.whipssh

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = WhipSshModule.NAME)
class WhipSshModule(reactContext: ReactApplicationContext) :
  NativeWhipSshSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, and ultimately
  // react-native-whip-ssh.cpp

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean
  external fun nativeDetachUi()
  external fun nativeSetDiagnosticPath(path: String)
  external fun nativeSetRecoveryDirectory(path: String)

  override fun invalidate() {
    nativeDetachUi()
    super.invalidate()
  }

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    nativeSetDiagnosticPath(java.io.File(context.noBackupFilesDir, "whip-runtime.log").absolutePath)
    nativeSetRecoveryDirectory(java.io.File(context.noBackupFilesDir, "reverse-control").absolutePath)
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  companion object {
    const val NAME = "WhipSsh"

    init {
      System.loadLibrary("react-native-whip-ssh")
    }
  }
}
