// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "react-native-whip-ssh.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

extern "C" void whip_set_background_monitoring_active(bool active);
extern "C" void whip_set_monitoring_network_available(bool available);
extern "C" void whip_detach_runtime_ui();
extern "C" void whip_set_runtime_diagnostic_path(const char *path);
extern "C" void whip_set_reverse_control_recovery_directory(const char *path);

extern "C" JNIEXPORT void JNICALL
Java_com_whipssh_WhipSshModule_nativeSetRecoveryDirectory(JNIEnv *env, jobject, jstring path) {
    const char *value = env->GetStringUTFChars(path, nullptr);
    if (value == nullptr) return;
    whip_set_reverse_control_recovery_directory(value);
    env->ReleaseStringUTFChars(path, value);
}

extern "C" JNIEXPORT void JNICALL
Java_com_whipssh_WhipSshModule_nativeSetDiagnosticPath(JNIEnv *env, jobject, jstring path) {
    const char *value = env->GetStringUTFChars(path, nullptr);
    if (value == nullptr) return;
    whip_set_runtime_diagnostic_path(value);
    env->ReleaseStringUTFChars(path, value);
}

extern "C" JNIEXPORT void JNICALL
Java_com_whipssh_WhipSshModule_nativeDetachUi(JNIEnv *, jobject) {
    whip_detach_runtime_ui();
}

extern "C" JNIEXPORT void JNICALL
Java_com_whipssh_HostRuntimeMonitoring_setBackgroundActive(JNIEnv *, jclass, jboolean active) {
    whip_set_background_monitoring_active(active == JNI_TRUE);
}

extern "C" JNIEXPORT void JNICALL
Java_com_whipssh_HostRuntimeMonitoring_setNetworkAvailable(JNIEnv *, jclass, jboolean available) {
    whip_set_monitoring_network_available(available == JNI_TRUE);
}

// Automated testing checks Java_com_whipssh_WhipSshModule and whipssh
// by comparing the whole line here.
/*
Java_com_whipssh_WhipSshModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return whipssh::multiply(a, b);
}
*/

// Installer coming from WhipSshModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_whipssh_WhipSshModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return whipssh::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_whipssh_WhipSshModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return whipssh::cleanupRustCrate(*runtime);
}
